# Generated by Django 2.2.4 on 2019-09-20 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_sesion', models.PositiveIntegerField(null=True)),
                ('url_img', models.URLField(null=True)),
                ('pred', models.CharField(max_length=8, null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('obs', models.CharField(max_length=200, null=True)),
                ('is_true', models.BooleanField(max_length=1, null=True)),
                ('consent', models.BooleanField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.CharField(max_length=100, null=True)),
                ('rol', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_paciente', models.PositiveIntegerField(null=True)),
                ('date', models.DateField()),
                ('obs', models.CharField(max_length=500, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('ced', models.CharField(max_length=10, null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('res', models.CharField(max_length=50, null=True)),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(max_length=40, null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
