# Generated by Django 2.2.4 on 2019-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('org', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=1)),
            ],
        ),
    ]
