# Generated by Django 2.2.4 on 2019-09-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='pred',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
