# Generated by Django 2.2.4 on 2019-09-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190926_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muestra',
            old_name='id_sesion',
            new_name='sesion',
        ),
    ]
