# Generated by Django 2.2.4 on 2019-10-24 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190926_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente_N',
            new_name='Paciente',
        ),
        migrations.AddField(
            model_name='sesion',
            name='id_usuario',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Paciente_A',
        ),
    ]
