# Generated by Django 2.2.4 on 2019-10-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191024_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='is_true',
        ),
        migrations.AddField(
            model_name='muestra',
            name='pred_true',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
